### ISSUE TITLE
What can be returned from _cluster in lmb.py?

### ISSUE THREAD

**Issue by iamlvm** [jonatanolofsson/lmb#2]
Your implementation of `_cluster` in `lmb.py` is to collect clusters of targets. I think this generator is used for _Grouping and Gating_ as shown in the below image.
![image](https://user-images.githubusercontent.com/15703029/106540933-4da87800-6544-11eb-9251-d06f25e21380.png)

Is your generator based on the below image? where __target groups are formed based on targets that share at least one measurement__.
![image](https://user-images.githubusercontent.com/15703029/106540641-b2170780-6543-11eb-9a68-06eb2744db19.png)

**Comment by jonatanolofsson** [comment]
Indeed, that grouping process is often referred to as clustering.

Note that not all steps in your first figure are necessary - see [1] for more details.

[1] Olofsson, J., Veibäck, C., & Hendeby, G. (2017). Sea ice tracking with a spatially indexed labeled multi-Bernoulli filter. In 20th International Conference on Information Fusion (FUSION). Xi’an, China.
